spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  datasource:
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver
    hikari:
      username: root
      password: 2000