logging:
  level:
    ROOT: WARN
    com.example: DEBUG

spring:
  application:
    name: ms-spring-boot
  messages:
    basename: i18n/messages
    encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  datasource:
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver
    hikari:
      username: root
      password: 2000
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mydb?createDatabaseIfNotExist=true
#    username: root
#    password: 2000

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1/sims

has:
  account: ${HAS_ACCOUNT:false}

student:
  names:
    - Jasur Ahmadov
    - Arnold Schwarzenegger

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs